apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  labels:
    app: {{.Values.name}}
  name: {{.Values.name}}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: {{.Values.name}}
        number: 31400
        protocol: TCP
        targetPort: 31400